FROM python:3.7
EXPOSE 8501

RUN apk update \
    && apk add curl

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["streamlit", "run", "src/index.py"]

